<section class="admin__page-section">
    <?php if ($block->isAndreaniViewOperation()) : ?>
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Items Shipped')) ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary order-shipment-table">
            <thead>
            <tr class="headings">
                <th class="col-product"><span><?= $block->escapeHtml(__('Product')) ?></span></th>
                <th class="col-qty last">
                    <span><?= $block->escapeHtml(__('Qty Shipped')) ?></span>
                </th>
            </tr>
            </thead>
            <?php $_items = $block->getAndreaniOrderItems();
            $_i = count($_items); ?>
            <tbody class="<?= $_i % 2 ? 'odd' : 'even' ?>">
            <?php foreach ($_items as $_item): ?>
                <tr>
                    <td class="col-product">
                        <div id="order_item_<?= (int)$_item->getId() ?>_title"
                             class="product-title">
                            <?= $block->escapeHtml($_item->getName()) ?>
                        </div>
                        <div class="product-sku-block">
                            <span><?= $block->escapeHtml(__('SKU')) ?>:</span> <?= /* @noEscape */
                            implode('<br />', $this->helper(\Magento\Catalog\Helper\Data::class)->splitSku($block->escapeHtml($_item->getSku()))) ?>
                        </div>
                    </td>
                    <td class="col-qty last">
                        <?= $_item->getQty() ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
            <?php else : ?>
            <div class="admin__page-section-title">
                <span class="title"><?= $block->escapeHtml(__('Items to Ship')) ?></span>
            </div>
            <div class="admin__table-wrapper">
                <table class="data-table admin__table-primary order-shipment-table">
                    <thead>
                    <tr class="headings">
                        <th class="col-product"><span><?= $block->escapeHtml(__('Product')) ?></span></th>
                        <th class="col-ordered-qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></th>
                        <th class="col-qty">
                            <span><?= $block->escapeHtml(__('Qty to Ship')) ?></span>
                        </th>
                    </tr>
                    </thead>
                    <?php $_items = $block->getOrder()->getAllItems() ?>
                    <?php $_i = 0;
                    foreach ($_items as $_item) :
                        if ($_item->getParentItem()) :
                            continue;
                        endif;
                        $_i++ ?>
                        <tbody class="<?= $_i % 2 ? 'odd' : 'even' ?>">
                        <tr>
                            <td class="col-product">
                                <div id="order_item_<?= (int)$_item->getId() ?>_title"
                                     class="product-title">
                                    <?= $block->escapeHtml($_item->getName()) ?>
                                </div>
                                <div class="product-sku-block">
                                    <span><?= $block->escapeHtml(__('SKU')) ?>:</span> <?= /* @noEscape */
                                    implode('<br />', $this->helper(\Magento\Catalog\Helper\Data::class)->splitSku($block->escapeHtml($_item->getSku()))) ?>
                                </div>
                            </td>
                            <td class="col-ordered-qty">
                                <table class="qty-table">
                                    <tr>
                                        <th><?= $block->escapeHtml(__('Ordered')); ?></th>
                                        <td><?= (float)$_item->getQtyOrdered() ?></td>
                                    </tr>

                                    <?php if ((float)$_item->getQtyInvoiced()) : ?>
                                        <tr>
                                            <th><?= $block->escapeHtml(__('Invoiced')); ?></th>
                                            <td><?= (float)$_item->getQtyInvoiced() ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ((float)$_item->getQtyShipped()) : ?>
                                        <tr>
                                            <th><?= $block->escapeHtml(__('Shipped')); ?></th>
                                            <td><?= (float)$_item->getQtyShipped() ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ((float)$_item->getQtyRefunded()) : ?>
                                        <tr>
                                            <th><?= $block->escapeHtml(__('Refunded')); ?></th>
                                            <td><?= (float)$_item->getQtyRefunded() ?></td>
                                        </tr>
                                    <?php endif; ?>

                                    <?php if ((float)$_item->getQtyCanceled()) : ?>
                                        <tr>
                                            <th><?= $block->escapeHtml(__('Canceled')); ?></th>
                                            <td><?= (float)$_item->getQtyCanceled() ?></td>
                                        </tr>
                                    <?php endif; ?>
                                </table>
                            </td>
                            <td class="col-qty">
                                <input type="text"
                                       class="input-text admin__control-text qty-item"
                                       value="<?= /* @noEscape */
                                       $_item->getQty() * 1 ?>"/>
                            </td>
                        </tr>
                        </tbody>
                    <?php endforeach; ?>
                    <?php endif; ?>
                </table>
            </div>
</section>


<script>
    require([
        "jquery",
        "Magento_Ui/js/modal/alert",
        "prototype"
    ], function (jQuery, alert) {

//<![CDATA[
        window.submitOperation = function (btn) {
            /*if (!validQtyItems()) {
                alert({
                    content: '<?= $block->escapeJs($block->escapeHtml(__('Invalid value(s) for Qty to Ship'))) ?>'
                });
                return;
            }*/
            alert({
                content: 'pasa por aca'
            })
            /*disableElements('submit-button');
            // Temporary solution will be replaced after refactoring order functionality
            jQuery('#edit_form').on('invalid-form.validate', function() {
                enableElements('submit-button');
                jQuery('#edit_form').off('invalid-form.validate');
            });
            jQuery('#edit_form').triggerHandler('save');*/
        }
        window.validQtyItems = function () {
            var valid = true;
            $$('.qty-item').each(function (item) {
                var val = parseFloat(item.value);
                if (isNaN(val) || val < 0) {
                    valid = false;
                }
            });
            return valid;
        }
//]]>

    });
</script>