<?php
//$failureDetail = $block->getData('errors');
//$failureCount = count($failureDetail);
//$totalCount = $block->getData('totalCount');
//if($failureCount == $totalCount){
//    $message = "Ningun pedido se genero con exito.";
//}
//else {
//    $message = strval($failureCount) . '/' . strval($totalCount) . " pedidos no se generaron con exito.";
//}
//?>
<!--<div>-->
<!--    <span>--><?php //echo $message ?><!--</span>-->
<!--    <a href="#"-->
<!--       data-mage-init='{"popupWindow": {"windowURL":"http://drubucloud.dyndns.org:12002/index.php/shipping/tracking/popup?hash=b3JkZXJfaWQ6NDY6ZTExMjA5MGFhY2FiODE5ZmJlMDViYzFhZGMwZjg2YTU%2C","windowName":"orderitems","width":1500,"height":700,"top":0,"left":0,"resizable":1,"scrollbars":1}}'-->
<!--    >-->
<!--        ver detalle-->
<!--    </a>-->
<!--</div>-->
<button type="submit" id="gotoreviewform" class="action submit primary write-action"><span>Click to Open</span></button>
<div id="popup-mpdal" style="display: none;" >
    <div class="message info notlogged" id="review-form">
        <div>
            <?php /* @noEscape */ echo __('Popup Modal Message!') ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    require(['jquery', 'Magento_Ui/js/modal/modal'], function($, modal){

        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            buttons: [{
                text: $.mage.__('Continue'),
                class: '',
                click: function () {
                    this.closeModal();
                }
            }]
        };
        var popup = modal(options, $('#popup-mpdal'));

        $(document).ready(function(){

            $("#gotoreviewform").click(function(){
                $('html, body').animate({
                    scrollTop: $("#review-form").offset().top
                }, 1000);

                $("#popup-mpdal").modal("openModal");
            });
        });
</script>